const NAME_OR_PASSWORD_IS_SPACE = 'NAME_OR_PASSWORD_IS_SPACE'
const USER_ALREADY_EXITS = 'USER_ALREADY_EXITS'
//用户名输入错误
const NOT_FIND_USER = "NOT_FIND_USER"
//密码输入错误
const ERR_PASSWORD = 'ERR_PASSWORD'
//token过期或未登录
const UN_LOGIN = 'UN_LOGIN'
//通过ID未能查找到评论
const CANT_FIND_CONTETN = 'CANT_FIND_CONTETN'
//无权修改评论
const NO_AUTH_CHANGE_MOMENT='NO_AUTH_CHANGE_MOMENT'
module.exports = {
    NAME_OR_PASSWORD_IS_SPACE,
    USER_ALREADY_EXITS,
    NOT_FIND_USER,
    ERR_PASSWORD, UN_LOGIN, CANT_FIND_CONTETN,NO_AUTH_CHANGE_MOMENT
}